# Generated by Django 3.0.10 on 2020-09-22 17:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('order_type', models.CharField(max_length=1, verbose_name='tipo')),
                ('client_code', models.CharField(max_length=128, verbose_name='código del tercero')),
                ('file_type', models.CharField(max_length=128, verbose_name='tipo de archivo')),
                ('company_code', models.CharField(max_length=12, verbose_name='compañia')),
                ('order_created_at', models.DateTimeField(verbose_name='fecha de la orden')),
                ('shipping_stimate_date', models.DateTimeField(verbose_name='fecha planificada de entrega')),
                ('currency', models.CharField(max_length=3, verbose_name='moneda')),
                ('buyer_fullname', models.CharField(max_length=512, verbose_name='nombre del comprador')),
                ('buyer_document', models.CharField(max_length=512, verbose_name='documento del comprador')),
                ('buyer_phone', models.CharField(max_length=512, verbose_name='teléfono del comprador')),
                ('buyer_email', models.EmailField(max_length=254, verbose_name='email del comprador')),
                ('shipping_address', models.TextField(verbose_name='dirección de envío')),
                ('shipping_address_city', models.TextField(verbose_name='ciudad de envío')),
                ('shipping_address_reference', models.TextField(verbose_name='referencia de dirección de envío')),
                ('shipping_address_zip', models.TextField(verbose_name='código postal')),
                ('warehouse_code', models.CharField(max_length=128, verbose_name='codDIrección de la cabecera')),
                ('order_number', models.CharField(max_length=30, verbose_name='No. pedido')),
                ('sell_type', models.CharField(max_length=56, verbose_name='tipo de venta')),
                ('sell_type_code', models.CharField(max_length=56, verbose_name='código tipo de venta')),
                ('payment_proof', models.CharField(max_length=56, verbose_name='Comprobante de pago')),
                ('seller_code', models.CharField(max_length=56, verbose_name='código del vendedor')),
                ('route_text_code', models.CharField(blank=True, max_length=56, null=True, verbose_name='codTextoRuta')),
                ('from_api', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('item_type', models.CharField(max_length=1, verbose_name='tipo')),
                ('item_number', models.IntegerField(verbose_name='consecutivo item')),
                ('ean', models.CharField(max_length=56, verbose_name='EAN')),
                ('item_qty', models.IntegerField(verbose_name='cantidad')),
                ('item_price_without_tax', models.FloatField(max_length=3, verbose_name='cantidad')),
                ('destination_address_code', models.CharField(max_length=56, verbose_name='Coddirección destino')),
                ('qty', models.IntegerField(verbose_name='cantidad 2')),
                ('tax_code', models.CharField(choices=[('000', '0%'), ('001', '19%')], max_length=3, verbose_name='código fiscal')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VtexClientOrder',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),
        migrations.CreateModel(
            name='VtexClientOrderItem',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.orderitem',),
        ),
    ]
